[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    vshymanskyy/TinyGSM @ ^0.11.7
    mikalhart/TinyGPSPlus @ ^1.0.3
    bblanchon/ArduinoJson @ ^6.21.3
    knolleary/PubSubClient @ ^2.8
    paulstoffregen/Time @ ^1.6.1
    tzapu/WiFiManager @ ^2.0.17
    lewisxhe/XPowersLib @ ^0.1.8
    